import type { CompanyFiling, DailyPoint, GapPoint, MacroPoint } from './series';

/**
 * The reading of the day, derived rather than written.
 *
 * Every figure here is computed from the observations the report already shows,
 * so it cannot say anything the tables do not, and it changes on its own as the
 * data does. That is deliberate: an analyst who is handed prose wants to be
 * able to check it line by line against the figures, and prose generated by a
 * model would have to be reviewed before it could be trusted at all.
 *
 * What it does not do is interpret. It states what moved, by how much, and
 * against what reference — never why, and never what comes next.
 *
 * Each reading is returned as a point rather than a paragraph: a label, the one
 * figure that is the news, which way it went, and the qualification underneath.
 * A day's reading is a checklist and not an essay, and a paragraph hides the
 * figure inside a sentence the eye has to read to the end of.
 */

export interface AnalysisInput {
  /** Latest calendar date with any observation at all. */
  latestDate: string | null;
  gap: GapPoint[];
  parallelBuy: DailyPoint[];
  parallelSell: DailyPoint[];
  official: DailyPoint[];
  ufv: DailyPoint[];
  filings: CompanyFiling[];
  macro: MacroPoint[];
}

/** Which way the figure moved, so the reader does not have to parse the sign. */
export type AnalysisTone = 'up' | 'down' | 'flat';

export interface AnalysisBullet {
  key: string;
  /** Name from the report's icon set; the view resolves it. */
  icon: string;
  label: string;
  /** The one figure that is the news, already formatted for reading. */
  value: string;
  /** What the figure did since the reference the detail names. */
  tone: AnalysisTone;
  /** The qualification: against what, since when, out of how many. */
  detail: string;
}

const number = (value: number, decimals = 2): string =>
  value.toLocaleString('es-BO', {
    minimumFractionDigits: decimals,
    maximumFractionDigits: decimals,
  });
const signed = (value: number, decimals = 2): string =>
  `${value > 0 ? '+' : value < 0 ? '−' : ''}${number(Math.abs(value), decimals)}`;
const longDate = (value: string): string =>
  new Intl.DateTimeFormat('es-BO', {
    day: '2-digit',
    month: 'long',
    year: 'numeric',
    timeZone: 'UTC',
  }).format(new Date(`${value}T12:00:00Z`));

/** A move only counts as a move once it would show in the printed figure. */
const toneOf = (move: number | null, threshold = 0.005): AnalysisTone => {
  if (move === null || Math.abs(move) < threshold) return 'flat';
  return move > 0 ? 'up' : 'down';
};

/** Mid-point of the two published sides on a given day. */
function midOn(buy: DailyPoint[], sell: DailyPoint[], date: string): number | null {
  const b = buy.find((point) => point.date === date)?.value;
  const s = sell.find((point) => point.date === date)?.value;
  return typeof b === 'number' && typeof s === 'number' ? (b + s) / 2 : null;
}

/**
 * The day's readings, in the order an analyst takes them: where the gap closed,
 * what the market did, what the administered rate did, what was filed, and the
 * annual context those daily figures sit inside.
 */
export function dailyAnalysis(input: AnalysisInput): {
  asOf: string | null;
  bullets: AnalysisBullet[];
} {
  const last = input.gap.at(-1);
  const previous = input.gap.at(-2);
  /**
   * The day being read is the last one with any observation, not the last one
   * with a gap. The gap needs two rates on the same day and can lag; anchoring
   * everything to it would report "no filings" for a day whose filings simply
   * arrived after the official rate did.
   */
  const asOf = input.latestDate ?? last?.date ?? null;
  const bullets: AnalysisBullet[] = [];

  if (!last) {
    return {
      asOf: null,
      bullets: [
        {
          key: 'sin-brecha',
          icon: 'info',
          label: 'Brecha cambiaria',
          value: 'sin dato',
          tone: 'flat',
          detail:
            'Ninguna jornada tiene cotización oficial y de mercado a la vez, de modo que la brecha no puede establecerse.',
        },
      ],
    };
  }

  // 1. The gap: level, daily move in points, distance from the period's peak.
  const peak = input.gap.reduce((best, point) =>
    point.gapPercent > best.gapPercent ? point : best,
  );
  const gapMove = previous ? last.gapPercent - previous.gapPercent : null;
  const gapIsCurrent = asOf === last.date;
  bullets.push({
    key: 'brecha',
    icon: 'balanza',
    label: 'Brecha cambiaria',
    value: `${signed(last.gapPercent)} %`,
    tone: toneOf(gapMove),
    detail:
      (gapIsCurrent
        ? `Al ${longDate(last.date)}`
        : `Al ${longDate(last.date)}, última jornada con ambas cotizaciones`) +
      (gapMove === null ? '.' : `, ${signed(gapMove)} puntos respecto a la jornada anterior.`) +
      (peak.date === last.date
        ? ' Es el máximo de la serie disponible.'
        : ` Queda ${number(peak.gapPercent - last.gapPercent)} puntos por debajo del máximo del periodo (${signed(peak.gapPercent)} %, ${longDate(peak.date)}).`),
  });

  // 2. The market rate: level, daily move, dispersion between venues.
  const mid = midOn(input.parallelBuy, input.parallelSell, last.date) ?? last.parallelMid;
  const previousMid = previous
    ? (midOn(input.parallelBuy, input.parallelSell, previous.date) ?? previous.parallelMid)
    : null;
  const midMove =
    previousMid && previousMid !== 0 ? ((mid - previousMid) / previousMid) * 100 : null;
  const sellToday = input.parallelSell.find((point) => point.date === last.date);
  const dispersion =
    sellToday && typeof sellToday.spread === 'number' && (sellToday.venues ?? 0) > 1
      ? ` Dispersión de ${number(sellToday.spread, 4)} Bs entre las ${sellToday.venues} plazas observadas.`
      : '';
  bullets.push({
    key: 'paralelo',
    icon: 'monedas',
    label: 'Dólar paralelo',
    value: `${number(mid, 4)} Bs/USD`,
    tone: toneOf(midMove),
    detail:
      (midMove === null
        ? 'Punto medio de las dos puntas publicadas.'
        : `Punto medio de las dos puntas publicadas, ${signed(midMove)} % en la jornada.`) +
      dispersion,
  });

  // 3. The administered rate, and whether it moved at all.
  const officialToday = input.official.find((point) => point.date === last.date);
  const officialMove = officialToday?.changePercent ?? null;
  bullets.push({
    key: 'oficial',
    icon: 'banco',
    label: 'Tipo de cambio oficial',
    value: `${number(last.official)} Bs/USD`,
    tone: toneOf(officialMove),
    detail:
      officialMove === null || Math.abs(officialMove) < 0.005
        ? 'Sin variación en la jornada; la cotización la administra el Banco Central.'
        : `Varió ${signed(officialMove)} % en la jornada.`,
  });

  // 4. The unit the country indexes contracts to, when the day published one.
  const ufv = input.ufv.at(-1);
  if (ufv) {
    bullets.push({
      key: 'ufv',
      icon: 'sigma',
      label: 'Unidad de Fomento de Vivienda',
      value: `${number(ufv.value, 5)} Bs/UFV`,
      tone: toneOf(ufv.changePercent ?? null, 0.0005),
      detail:
        ufv.changePercent === null
          ? `Valor publicado para el ${longDate(ufv.date)}.`
          : `${signed(ufv.changePercent, 4)} % respecto al día anterior; es la unidad a la que se indexan contratos y créditos.`,
    });
  }

  // 5. What the exchange registered that day.
  const sameDay = input.filings.filter((filing) => filing.eventDate === asOf);
  const filers = [...new Set(sameDay.map((filing) => filing.filer))];
  bullets.push({
    key: 'bbv',
    icon: 'edificio',
    label: 'Bolsa Boliviana de Valores',
    value:
      sameDay.length === 0
        ? 'sin registros'
        : `${sameDay.length} hecho${sameDay.length === 1 ? '' : 's'}`,
    tone: 'flat',
    detail:
      sameDay.length === 0
        ? `No se registraron hechos relevantes el ${longDate(asOf ?? last.date)}.`
        : `Hechos relevantes de ${filers.length} emisor${filers.length === 1 ? '' : 'es'} el ${longDate(asOf ?? last.date)}.`,
  });

  // 6. The structural anchors, stated only as the year they belong to.
  const inflation = input.macro
    .filter((point) => point.indicatorCode === 'CPI_INFLATION_ANNUAL_PCT')
    .at(-1);
  if (inflation) {
    bullets.push({
      key: 'inflacion',
      icon: 'etiqueta',
      label: 'Inflación anual',
      value: `${number(inflation.value)} %`,
      tone: toneOf(inflation.changePercent ?? null),
      detail: `Último año publicado por la fuente anual (${inflation.period}).`,
    });
  }

  const reserves = input.macro
    .filter((point) => point.indicatorCode === 'INTERNATIONAL_RESERVES_USD')
    .at(-1);
  if (reserves) {
    bullets.push({
      key: 'reservas',
      icon: 'escudo',
      label: 'Reservas internacionales',
      value: `${number(reserves.value / 1_000_000, 0)} M USD`,
      tone: toneOf(reserves.changePercent ?? null),
      detail:
        reserves.changePercent === null
          ? `Saldo del año ${reserves.period}.`
          : `Saldo del año ${reserves.period}, ${signed(reserves.changePercent)} % frente al año anterior.`,
    });
  }

  return { asOf, bullets };
}
