import type { CompanyFiling, DailyPoint, GapPoint, MacroPoint } from './series';

/**
 * The reading of the day, derived rather than written.
 *
 * Every sentence here is computed from the observations the report already
 * shows, so it cannot say anything the tables do not, and it changes on its own
 * as the data does. That is deliberate: an analyst who is handed prose wants to
 * be able to check it line by line against the figures, and prose generated by
 * a model would have to be reviewed before it could be trusted at all.
 *
 * What it does not do is interpret. It states what moved, by how much, and
 * against what reference — never why, and never what comes next.
 */

export interface AnalysisInput {
  /** Latest calendar date with any observation at all. */
  latestDate: string | null;
  gap: GapPoint[];
  parallelBuy: DailyPoint[];
  parallelSell: DailyPoint[];
  official: DailyPoint[];
  ufv: DailyPoint[];
  filings: CompanyFiling[];
  macro: MacroPoint[];
}

const number = (value: number, decimals = 2): string =>
  value.toLocaleString('es-BO', {
    minimumFractionDigits: decimals,
    maximumFractionDigits: decimals,
  });
const signed = (value: number, decimals = 2): string =>
  `${value > 0 ? '+' : value < 0 ? '−' : ''}${number(Math.abs(value), decimals)}`;
const longDate = (value: string): string =>
  new Intl.DateTimeFormat('es-BO', {
    day: '2-digit',
    month: 'long',
    year: 'numeric',
    timeZone: 'UTC',
  }).format(new Date(`${value}T12:00:00Z`));

/** Mid-point of the two published sides on a given day. */
function midOn(buy: DailyPoint[], sell: DailyPoint[], date: string): number | null {
  const b = buy.find((point) => point.date === date)?.value;
  const s = sell.find((point) => point.date === date)?.value;
  return typeof b === 'number' && typeof s === 'number' ? (b + s) / 2 : null;
}

/**
 * Sentences for the day, in the order an analyst reads them: where the gap
 * closed, what the market did, what the administered rate did, and what was
 * filed.
 */
export function dailyAnalysis(input: AnalysisInput): { asOf: string | null; lines: string[] } {
  const last = input.gap.at(-1);
  const previous = input.gap.at(-2);
  /**
   * The day being read is the last one with any observation, not the last one
   * with a gap. The gap needs two rates on the same day and can lag; anchoring
   * everything to it would report "no filings" for a day whose filings simply
   * arrived after the official rate did.
   */
  const asOf = input.latestDate ?? last?.date ?? null;
  const lines: string[] = [];

  if (!last) {
    return {
      asOf: null,
      lines: [
        'No hay ninguna jornada con cotización oficial y de mercado a la vez, de modo que la brecha no puede establecerse.',
      ],
    };
  }

  // 1. The gap: level, daily move in points, distance from the period's peak.
  const peak = input.gap.reduce((best, point) =>
    point.gapPercent > best.gapPercent ? point : best,
  );
  const gapMove = previous ? last.gapPercent - previous.gapPercent : null;
  const gapIsCurrent = asOf === last.date;
  lines.push(
    `La brecha cambiaria${gapIsCurrent ? ` al ${longDate(last.date)}` : `, al ${longDate(last.date)}, última jornada con ambas cotizaciones,`} se situó en ${signed(last.gapPercent)} %` +
      (gapMove === null ? '.' : `, ${signed(gapMove)} puntos respecto a la jornada anterior.`) +
      (peak.date === last.date
        ? ' Es el máximo de la serie disponible.'
        : ` Queda ${number(peak.gapPercent - last.gapPercent)} puntos por debajo del máximo del periodo (${signed(peak.gapPercent)} %, ${longDate(peak.date)}).`),
  );

  // 2. The market rate: level, daily move, dispersion between venues.
  const mid = midOn(input.parallelBuy, input.parallelSell, last.date) ?? last.parallelMid;
  const previousMid = previous
    ? (midOn(input.parallelBuy, input.parallelSell, previous.date) ?? previous.parallelMid)
    : null;
  const midMove =
    previousMid && previousMid !== 0 ? ((mid - previousMid) / previousMid) * 100 : null;
  const sellToday = input.parallelSell.find((point) => point.date === last.date);
  const dispersion =
    sellToday && typeof sellToday.spread === 'number' && (sellToday.venues ?? 0) > 1
      ? ` La dispersión entre las ${sellToday.venues} plazas observadas fue de ${number(sellToday.spread, 4)} Bs.`
      : '';
  lines.push(
    `El punto medio del dólar paralelo cerró en ${number(mid, 4)} Bs/USD` +
      (midMove === null ? '.' : `, ${signed(midMove)} % en la jornada.`) +
      dispersion,
  );

  // 3. The administered rate, and whether it moved at all.
  const officialToday = input.official.find((point) => point.date === last.date);
  const officialMove = officialToday?.changePercent ?? null;
  lines.push(
    `El tipo de cambio oficial ${officialMove === null || Math.abs(officialMove) < 0.005 ? 'se mantuvo' : `varió ${signed(officialMove)} %`} en ${number(last.official)} Bs/USD.` +
      (input.ufv.at(-1)
        ? ` La UFV del día es ${number(input.ufv.at(-1)?.value ?? 0, 5)} Bs/UFV.`
        : ''),
  );

  // 4. What the exchange registered that day.
  const sameDay = input.filings.filter((filing) => filing.eventDate === asOf);
  const filers = [...new Set(sameDay.map((filing) => filing.filer))];
  lines.push(
    sameDay.length === 0
      ? `La Bolsa Boliviana de Valores no registró hechos relevantes el ${longDate(asOf ?? last.date)}.`
      : `La Bolsa Boliviana de Valores registró ${sameDay.length} hecho${sameDay.length === 1 ? '' : 's'} relevante${sameDay.length === 1 ? '' : 's'} de ${filers.length} emisor${filers.length === 1 ? '' : 'es'}.`,
  );

  // 5. The structural anchor, stated only as the year it belongs to.
  const inflation = input.macro
    .filter((point) => point.indicatorCode === 'CPI_INFLATION_ANNUAL_PCT')
    .at(-1);
  const reserves = input.macro
    .filter((point) => point.indicatorCode === 'INTERNATIONAL_RESERVES_USD')
    .at(-1);
  if (inflation && reserves) {
    lines.push(
      `Contexto anual más reciente (${inflation.period}): inflación de ${number(inflation.value)} % y reservas internacionales por ${number(reserves.value / 1_000_000, 0)} millones de dólares` +
        (reserves.changePercent === null
          ? '.'
          : `, ${signed(reserves.changePercent)} % frente al año anterior.`),
    );
  }

  return { asOf, lines };
}
