/**
 * The reading of the exchange rate, derived rather than written.
 *
 * Every sentence here is assembled from figures the same page charts, so a
 * reader can check it line by line against the tables, and it changes on its
 * own as the data does. That is deliberate twice over: prose generated by a
 * model would have to be reviewed before it could be trusted at all, and prose
 * written by hand goes stale the first time the data moves.
 *
 * What it does not do is explain. It states the level, the reference and the
 * regime — never the cause, never what comes next.
 *
 * The order is the order the questions actually arrive in for someone holding
 * bolivianos. Not "how volatile was it", which is where this section used to
 * start, but: is a dollar scarce, which regime is this, is the currency really
 * cheaper, how fast are prices moving, and what does the rail cost.
 *
 * Kept apart from `fx-macro.ts` so that the arithmetic stays testable without
 * the wording, and the wording can change without touching a figure.
 */

import {
  detectRegimes,
  gapProfile,
  impliedInflation,
  realIndex,
  type FxRegime,
  type GapProfile,
  type GapReading,
  type MacroPoint,
  type RegimeSegment,
} from './fx-macro';

export interface StablecoinReading {
  token: string;
  mid: number;
  bid: number | null;
  ask: number | null;
  venues: number;
  date: string;
  /** Round-trip cost through this rail, as a percentage of the mid-point. */
  spreadPercent: number | null;
  /**
   * How much dearer this rail's mid-point is than the cheapest rail read.
   *
   * The mid is the robust comparison — it cannot be moved by one wide side — so
   * it is what the series charts.
   */
  premiumPercent: number | null;
  /**
   * How much dearer it is **to buy** a dollar here than through the cheapest
   * rail read.
   *
   * Kept beside the mid premium rather than instead of it because the two answer
   * different questions and differ by more than rounding: a rail with a wide
   * spread can sit near the middle of the market and still be the expensive
   * place to buy. This is the figure to quote whenever the sentence says
   * "buying", and quoting the mid there would understate what the reader pays.
   */
  premiumAskPercent: number | null;
}

/** Which way a figure points for whoever holds bolivianos. */
export type ConclusionTone = 'adverse' | 'favourable' | 'neutral';

export interface FxConclusion {
  key: string;
  /** The claim in words, with no figure buried inside the sentence. */
  claim: string;
  /** The figure that is the news, already formatted for reading. */
  figure: string;
  /** What qualifies it: against what, since when, under which regime. */
  detail: string;
  tone: ConclusionTone;
}

export interface FxSnapshot {
  asOf: string | null;
  official: MacroPoint | null;
  parallelMid: MacroPoint | null;
  gap: GapProfile;
  regime: FxRegime;
  regimes: RegimeSegment[];
  /** Base-100 real levels, and the date they are indexed to. */
  real: { officialIndex: number; parallelIndex: number; base: string } | null;
  /** Annualised inflation implied by the UFV over the trailing year. */
  impliedInflationAnnual: number | null;
  stablecoins: StablecoinReading[];
  conclusions: FxConclusion[];
}

export interface StablecoinInput {
  token: string;
  sidesResolved: boolean;
  points: ReadonlyArray<{
    date: string;
    mid: number;
    bid: number | null;
    ask: number | null;
    venues: number;
  }>;
}

export interface FxMacroInput {
  official: readonly MacroPoint[];
  parallelMid: readonly MacroPoint[];
  ufv: readonly MacroPoint[];
  gap: readonly GapReading[];
  stablecoins: readonly StablecoinInput[];
}

const say = (value: number, decimals = 2): string =>
  value.toLocaleString('es-BO', {
    minimumFractionDigits: decimals,
    maximumFractionDigits: decimals,
  });
const signed = (value: number, decimals = 2): string =>
  `${value > 0 ? '+' : value < 0 ? '−' : ''}${say(Math.abs(value), decimals)}`;
const longDate = (value: string): string =>
  new Intl.DateTimeFormat('es-BO', {
    day: '2-digit',
    month: 'long',
    year: 'numeric',
    timeZone: 'UTC',
  }).format(new Date(`${value}T12:00:00Z`));

/** The gap, read against its own maximum rather than on its own. */
function gapConclusion(gap: GapProfile): FxConclusion | null {
  if (!gap.current || !gap.peak) return null;
  const closed = gap.peak.gapPercent - gap.current.gapPercent;
  const nearlyClosed = gap.current.gapPercent < 10 && gap.peak.gapPercent > 40;
  return {
    key: 'brecha',
    claim: nearlyClosed
      ? 'La brecha cambiaria está prácticamente cerrada'
      : 'Distancia entre el dólar oficial y el de mercado',
    figure: `${signed(gap.current.gapPercent)} %`,
    detail:
      `Al ${longDate(gap.current.date)}. Llegó a ${signed(gap.peak.gapPercent)} % el ` +
      `${longDate(gap.peak.date)}, de modo que se cerraron ${say(closed)} puntos desde ese ` +
      `máximo` +
      (gap.daysInverted > 0
        ? `. En ${gap.daysInverted} de ${gap.observations} jornadas el oficial cotizó por ` +
          `encima del mercado, que es la señal de que la corrección se pasó de largo.`
        : '.'),
    tone: gap.current.gapPercent > 20 ? 'adverse' : 'favourable',
  };
}

/**
 * Which regime this is, and the warning that comes with it.
 *
 * Stated second and not last because it qualifies everything else on the page:
 * a statistic computed across the change describes neither stretch.
 */
function regimeConclusion(regimes: readonly RegimeSegment[]): FxConclusion | null {
  const current = regimes.at(-1);
  if (!current) return null;
  const previous = regimes.at(-2);
  const moving = current.regime === 'EN_MOVIMIENTO';
  return {
    key: 'regimen',
    claim: moving
      ? 'El tipo de cambio oficial ya no está fijo: se mueve'
      : 'El tipo de cambio oficial está administrado y quieto',
    figure: `${say(current.days, 0)} días`,
    detail:
      (moving
        ? `Se mueve desde el ${longDate(current.from)}, de ${say(current.rateFrom)} a ` +
          `${say(current.rateTo)} Bs/USD.`
        : `Sin variación desde el ${longDate(current.from)}, en ${say(current.rateTo)} Bs/USD.`) +
      (previous
        ? ` Antes estuvo ${previous.regime === 'FIJO' ? 'fijo' : 'en movimiento'} ` +
          `${say(previous.days, 0)} días. Ninguna estadística que cruce esa fecha describe los ` +
          `dos tramos a la vez.`
        : ''),
    tone: 'neutral',
  };
}

/**
 * Whether the dollar is genuinely dearer or only nominally so.
 *
 * This is the conclusion the old panel had no way of reaching, and on this data
 * it reverses what the level chart suggests.
 */
function realConclusion(
  parallel: readonly MacroPoint[],
  realParallel: readonly MacroPoint[],
  base: string,
): FxConclusion | null {
  const now = realParallel.at(-1);
  const first = parallel.at(0);
  const last = parallel.at(-1);
  if (!now || !first || !last || first.value === 0) return null;
  const nominalChange = (last.value / first.value - 1) * 100;
  const realChange = now.value - 100;
  const cheaper = realChange < 0;
  return {
    key: 'real',
    claim: cheaper
      ? 'Descontada la inflación, el dólar está más barato que al inicio de la serie'
      : 'Descontada la inflación, el dólar está más caro que al inicio de la serie',
    figure: `${signed(realChange, 1)} % real`,
    detail:
      `En bolivianos corrientes subió ${signed(nominalChange, 1)} % desde el ${longDate(base)}, ` +
      `pero los precios subieron ${cheaper ? 'más' : 'menos'}, así que medido en poder de compra ` +
      `${cheaper ? 'cayó' : 'subió'} ${say(Math.abs(realChange), 1)} %. Índice ` +
      `${say(now.value, 1)} sobre base 100, deflactado con la UFV, que el Banco Central publica ` +
      `todos los días.`,
    tone: cheaper ? 'favourable' : 'adverse',
  };
}

/** What holding the official rate still cost in competitiveness. */
function anchorConclusion(
  regimes: readonly RegimeSegment[],
  realOfficial: readonly MacroPoint[],
): FxConclusion | null {
  const pegEnd = regimes.find((segment) => segment.regime === 'EN_MOVIMIENTO')?.from;
  if (!pegEnd) return null;
  const atPegEnd = realOfficial.filter((point) => point.date < pegEnd).at(-1);
  const now = realOfficial.at(-1);
  if (!atPegEnd || !now || atPegEnd.value >= 95) return null;
  return {
    key: 'ancla',
    claim: 'Mantener el oficial quieto le costó competitividad al tipo de cambio',
    figure: `${signed(atPegEnd.value - 100, 1)} % real`,
    detail:
      `Con el oficial clavado y los precios subiendo, su nivel real cayó hasta ` +
      `${say(atPegEnd.value, 1)} el ${longDate(atPegEnd.date)}, la víspera de que empezara a ` +
      `moverse: el mismo número de bolivianos compraba cada vez menos dólar de verdad. Hoy está ` +
      `en ${say(now.value, 1)}, de modo que la corrección ` +
      `${now.value >= 100 ? 'recuperó el terreno perdido' : 'aún no lo recupera'}.`,
    tone: 'neutral',
  };
}

/** Prices, at the only frequency this report can measure them daily. */
function inflationConclusion(inflation: MacroPoint | null): FxConclusion | null {
  if (!inflation) return null;
  return {
    key: 'inflacion',
    claim: 'Inflación implícita en la UFV, últimos doce meses',
    figure: `${say(inflation.value, 1)} %`,
    detail:
      `Al ${longDate(inflation.date)}, leída de la unidad a la que se indexan los contratos y ` +
      `el crédito. Es la única medida de precios que este informe tiene a frecuencia diaria: la ` +
      `serie anual del compilador multilateral llega una vez al año y con retraso.`,
    tone: inflation.value > 10 ? 'adverse' : inflation.value > 5 ? 'neutral' : 'favourable',
  };
}

/**
 * What the rail costs, stated only where two tokens were read the same day.
 *
 * Quoted on the **ask** whenever both rails published one, because the sentence
 * is about buying and buying happens at the ask. The mid premium is the fallback
 * and the wording changes with it: the two figures differ by more than rounding
 * — a rail can sit near the middle of the market and still be the dear place to
 * buy — so saying "buying" over a mid-point number would understate what the
 * reader actually pays.
 */
function railConclusion(readings: readonly StablecoinReading[]): FxConclusion | null {
  if (readings.length < 2) return null;
  const onAsk = readings.filter((reading) => reading.premiumAskPercent !== null).at(-1);
  const dearest = onAsk ?? readings.filter((reading) => reading.premiumPercent !== null).at(-1);
  const premium = onAsk ? onAsk.premiumAskPercent : dearest?.premiumPercent;
  if (!dearest || !premium) return null;
  return {
    key: 'riel',
    claim: onAsk
      ? `Comprar dólares en ${dearest.token} sale más caro que por el riel más barato`
      : `El dólar en ${dearest.token} cotiza por encima del riel más barato`,
    figure: `${signed(premium)} %`,
    detail:
      `Al ${longDate(dearest.date)}, con ${say(dearest.venues, 0)} ` +
      `plaza${dearest.venues === 1 ? '' : 's'} cotizando` +
      (onAsk
        ? ` y comparando lo que se paga en cada riel (${say(dearest.ask ?? 0)} Bs/USD aquí)`
        : ' y comparando puntos medios') +
      (dearest.spreadPercent !== null
        ? `. Ida y vuelta por este riel cuesta ${say(dearest.spreadPercent)} %`
        : '') +
      `. Esa diferencia es el precio del riel y no el de otro dólar: las dos son fichas ` +
      `ancladas al mismo dólar.`,
    tone: 'adverse',
  };
}

/**
 * The latest reading of each token, with what its rail costs on top.
 *
 * The premium is measured against the cheapest token read **that same day**
 * rather than against a fixed reference, because which rail is cheapest is
 * itself the thing that moves. A token last read on a different day is left
 * without a premium instead of being compared across dates.
 */
export function stablecoinPremium(series: readonly StablecoinInput[]): StablecoinReading[] {
  const latest = series.flatMap((entry) => {
    const point = entry.points.at(-1);
    if (!point) return [];
    const sided = entry.sidesResolved && point.bid !== null && point.ask !== null;
    return [
      {
        token: entry.token,
        date: point.date,
        mid: point.mid,
        bid: point.bid,
        ask: point.ask,
        venues: point.venues,
        spreadPercent:
          sided && point.mid > 0 ? (((point.ask ?? 0) - (point.bid ?? 0)) / point.mid) * 100 : null,
      },
    ];
  });

  const latestDate = [...latest.map((reading) => reading.date)].sort().at(-1);
  const sameDay = latest.filter((reading) => reading.date === latestDate);
  /*
   * Both references come from the same day and only exist with something to
   * compare against: a single rail has no premium, and a rail measured on
   * another date would be compared across a move rather than across a market.
   */
  const cheapestMid = sameDay.length > 1 ? Math.min(...sameDay.map((entry) => entry.mid)) : null;
  const asks = sameDay.flatMap((entry) => (entry.ask === null ? [] : [entry.ask]));
  const cheapestAsk = asks.length > 1 ? Math.min(...asks) : null;

  const against = (value: number | null, reference: number | null): number | null =>
    value !== null && reference !== null && reference > 0 && value !== reference
      ? (value / reference - 1) * 100
      : null;

  return latest
    .map((reading) => ({
      ...reading,
      premiumPercent: reading.date === latestDate ? against(reading.mid, cheapestMid) : null,
      premiumAskPercent: reading.date === latestDate ? against(reading.ask, cheapestAsk) : null,
    }))
    .sort((left, right) => left.mid - right.mid);
}

/** Assembles the whole reading from series the report already holds. */
export function fxSnapshot(input: FxMacroInput): FxSnapshot {
  const official = [...input.official].sort((left, right) => left.date.localeCompare(right.date));
  const parallel = [...input.parallelMid].sort((left, right) =>
    left.date.localeCompare(right.date),
  );
  const gap = gapProfile(input.gap);
  const regimes = detectRegimes(official);

  const base = parallel.at(0)?.date;
  const realParallel = base ? realIndex(parallel, input.ufv, base) : [];
  const realOfficial = base
    ? realIndex(
        official.filter((point) => point.date >= base),
        input.ufv,
        base,
      )
    : [];
  const inflation = impliedInflation(input.ufv).at(-1) ?? null;
  const stablecoins = stablecoinPremium(input.stablecoins);

  const conclusions = [
    gapConclusion(gap),
    regimeConclusion(regimes),
    base ? realConclusion(parallel, realParallel, base) : null,
    anchorConclusion(regimes, realOfficial),
    inflationConclusion(inflation),
    railConclusion(stablecoins),
  ].filter((entry): entry is FxConclusion => entry !== null);

  const realNow = realParallel.at(-1);
  const realOfficialNow = realOfficial.at(-1);

  return {
    asOf: parallel.at(-1)?.date ?? official.at(-1)?.date ?? null,
    official: official.at(-1) ?? null,
    parallelMid: parallel.at(-1) ?? null,
    gap,
    regime: regimes.at(-1)?.regime ?? 'FIJO',
    regimes,
    real:
      realNow && realOfficialNow && base
        ? { officialIndex: realOfficialNow.value, parallelIndex: realNow.value, base }
        : null,
    impliedInflationAnnual: inflation?.value ?? null,
    stablecoins,
    conclusions,
  };
}
